name: Validate

on:
  push:
    branches:
      - 'main'
  workflow_call:

concurrency:
  group: validate-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: 'Typecheck'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: pnpm install

      - name: Run typechecker
        run: pnpm typecheck

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint

  knip:
    name: 'Knip'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: pnpm install

      - name: Run knip
        run: pnpm knip
