name: Validate

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  validate-templates:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        template:
          - frontend-vue
          - no-frontend

    steps:
      - name: Checkout project
        uses: actions/checkout@v7

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Install dependencies
        run: pnpm install
        working-directory: templates/${{ matrix.template }}

      - name: Build
        run: pnpm build
        working-directory: templates/${{ matrix.template }}

      - name: Typecheck
        run: pnpm typecheck
        working-directory: templates/${{ matrix.template }}

      - name: Lint
        run: pnpm lint
        working-directory: templates/${{ matrix.template }}

  typecheck:
    name: 'Typecheck'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run typechecker
        run: pnpm typecheck

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint

  test:
    name: 'Test'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
